# theme.toml template for a Hugo theme

name = "KOS-IT"
license = "MIT"
licenselink = "https://github.com/lubang/hugo-hello-programmer-theme/blob/master/LICENSE.md"
description = "Making and Developing"
homepage = "https://kos-it.github.com/"
tags = ["blog", "3D modeling", "desain grafis", "game making", "programmer", "website"]
features = ["blog", "simple", "programmer"]
min_version = 0.15

[author]
  name = "Karcaqs"
  homepage = "https://kos-it.github.com/about/"
