baseurl = "https://kos-it.github.io"
title = "KOS-IT — Making and Developing"
languageCode = "id-id"

theme = "programmer"
themesdir = "themes"

paginate = 4

disqusShortname = "kos-it-github-io"
googleAnalytics = "UA-XXXXXXXX-X"

[author]
    name = "Karcaqs"
    homepage = "https://web.facebook.com/taqwa.prakoso"
    bio = "Sejenis Terong"
    image = "/img/karcaqs.svg"
    email = "taqwaalmutawakkil97@gmail.com"


#[markup]
#    [markup.highlight]
#        codeFences = true
#        guessSyntax = false
#        hl_Lines = ""
#        lineNoStart = 1
#        lineNos = false
#        lineNumbersInTable = true
#        noClasses = true
#        style = "monokai"
#        tabWidth = 4
#    [markup.tableOfContents]
#        endLevel = 3
#        ordered = false
#        startLevel = 2

#pygmentscodefences = true
#pygmentscodefencesguesssyntax = true
#pygmentsoptions = ""
pygmentsstyle = "monokai"
pygmentsuseclasses = true
#pygmentsuseclassic = false